/**
 * Phase 11 brand catalog — luxury / collector houses for ArchiveX domains.
 * Cars & motorcycles primary; watches secondary. Seeded as active operator content.
 *
 * `key` is optional — used by seedDemo product wiring for short lookups.
 */
export const BRAND_CATALOG = [
  // —— Cars (primary) ——
  { key: 'mercedes', slug: 'mercedes-benz', name: 'Mercedes-Benz', country: 'Germany', foundedYear: 1926, domains: ['car'], description: 'Stuttgart house of engineering and rare competition silhouettes.' },
  { key: 'ferrari', slug: 'ferrari', name: 'Ferrari', country: 'Italy', foundedYear: 1947, domains: ['car'], description: 'Maranello icons spanning racing myth and road legend.' },
  { key: 'bugatti', slug: 'bugatti', name: 'Bugatti', country: 'France', foundedYear: 1909, domains: ['car'], description: 'Molsheim hypercar craft and horseshoe-grille theatre.' },
  { key: 'porsche', slug: 'porsche', name: 'Porsche', country: 'Germany', foundedYear: 1931, domains: ['car'], description: 'Enduring sports-car geometry and collector continuity.' },
  { key: 'lamborghini', slug: 'lamborghini', name: 'Lamborghini', country: 'Italy', foundedYear: 1963, domains: ['car'], description: 'Sant’Agata wedge drama and V10/V12 presence.' },
  { key: 'mclaren', slug: 'mclaren', name: 'McLaren', country: 'United Kingdom', foundedYear: 1963, domains: ['car'], description: 'Woking hybrid hypercar craftsmanship.' },
  { slug: 'aston-martin', name: 'Aston Martin', country: 'United Kingdom', foundedYear: 1913, domains: ['car'], description: 'Gaydon grand-touring elegance and Bond-era mythology.' },
  { slug: 'bentley', name: 'Bentley', country: 'United Kingdom', foundedYear: 1919, domains: ['car'], description: 'Crewe coachbuilt power and hand-finished interiors.' },
  { slug: 'rolls-royce', name: 'Rolls-Royce', country: 'United Kingdom', foundedYear: 1904, domains: ['car'], description: 'Goodwood presence, Spirit of Ecstasy, and quiet theatre.' },
  { slug: 'bmw', name: 'BMW', country: 'Germany', foundedYear: 1916, domains: ['car'], description: 'Munich sports-saloon language and M-division lore.' },
  { slug: 'audi', name: 'Audi', country: 'Germany', foundedYear: 1909, domains: ['car'], description: 'Ingolstadt quattro engineering and Bauhaus surfaces.' },
  { slug: 'jaguar', name: 'Jaguar', country: 'United Kingdom', foundedYear: 1922, domains: ['car'], description: 'Coventry feline sports cars and E-Type silhouette memory.' },
  { slug: 'maserati', name: 'Maserati', country: 'Italy', foundedYear: 1914, domains: ['car'], description: 'Modena trident sports cars and grand-touring song.' },
  { slug: 'alfa-romeo', name: 'Alfa Romeo', country: 'Italy', foundedYear: 1910, domains: ['car'], description: 'Milanese sporting heart and competition heritage.' },
  { slug: 'pagani', name: 'Pagani', country: 'Italy', foundedYear: 1992, domains: ['car'], description: 'Modena hypercar artistry and carbon-titanium craft.' },
  { slug: 'koenigsegg', name: 'Koenigsegg', country: 'Sweden', foundedYear: 1994, domains: ['car'], description: 'Ängelholm megacar engineering and ghost-plated rarity.' },
  { slug: 'lotus', name: 'Lotus', country: 'United Kingdom', foundedYear: 1952, domains: ['car'], description: 'Hethel light-weight doctrine and Chapman geometry.' },
  { slug: 'alpine', name: 'Alpine', country: 'France', foundedYear: 1955, domains: ['car'], description: 'Dieppe sports cars with rally DNA and blue livery lore.' },
  { slug: 'cadillac', name: 'Cadillac', country: 'United States', foundedYear: 1902, domains: ['car'], description: 'American luxury crest and V-series performance.' },
  { slug: 'lexus', name: 'Lexus', country: 'Japan', foundedYear: 1989, domains: ['car'], description: 'Toyota luxury division with F and LFA collector presence.' },
  { slug: 'land-rover', name: 'Land Rover', country: 'United Kingdom', foundedYear: 1948, domains: ['car'], description: 'Solihull off-road aristocracy and Defender continuity.' },
  { slug: 'range-rover', name: 'Range Rover', country: 'United Kingdom', foundedYear: 1970, domains: ['car'], description: 'Luxury go-anywhere silhouette and estate theatre.' },
  { slug: 'nissan', name: 'Nissan', country: 'Japan', foundedYear: 1933, domains: ['car'], description: 'GT-R mythology and Z-car sports lineage.' },
  { slug: 'toyota', name: 'Toyota', country: 'Japan', foundedYear: 1937, domains: ['car'], description: 'Supra and Century collector paths beyond volume production.' },
  { slug: 'honda-cars', name: 'Honda Cars', country: 'Japan', foundedYear: 1948, domains: ['car'], description: 'NSX mid-engine lore and Type R road craft.' },
  { slug: 'mazda', name: 'Mazda', country: 'Japan', foundedYear: 1920, domains: ['car'], description: 'Hiroshima rotary myth and MX-5 lightness.' },
  { slug: 'subaru', name: 'Subaru', country: 'Japan', foundedYear: 1953, domains: ['car'], description: 'Boxer rally heritage and STI collector interest.' },
  { slug: 'ford', name: 'Ford', country: 'United States', foundedYear: 1903, domains: ['car'], description: 'GT and Mustang performance plates in the American archive.' },
  { slug: 'chevrolet', name: 'Chevrolet', country: 'United States', foundedYear: 1911, domains: ['car'], description: 'Corvette sports-car lineage and muscle-era memory.' },
  { slug: 'de-tomaso', name: 'De Tomaso', country: 'Italy', foundedYear: 1959, domains: ['car'], description: 'Modena–Argentine Pantera wedge and racing ambition.' },
  { slug: 'lancia', name: 'Lancia', country: 'Italy', foundedYear: 1906, domains: ['car'], description: 'Turin engineering poetry and rally Stratos myth.' },
  { slug: 'morgan', name: 'Morgan', country: 'United Kingdom', foundedYear: 1910, domains: ['car'], description: 'Malvern ash-frame roadsters and hand-built continuity.' },
  { slug: 'tvr', name: 'TVR', country: 'United Kingdom', foundedYear: 1947, domains: ['car'], description: 'Blackpool fiberglass sports cars and untamed V8 character.' },
  { slug: 'rimac', name: 'Rimac', country: 'Croatia', foundedYear: 2009, domains: ['car'], description: 'Sveta Nedelja electric hypercar engineering.' },
  { slug: 'spyker', name: 'Spyker', country: 'Netherlands', foundedYear: 1898, domains: ['car'], description: 'Dutch aviation-inspired coachwork and scarce road cars.' },
  { slug: 'zenvo', name: 'Zenvo', country: 'Denmark', foundedYear: 2007, domains: ['car'], description: 'Præstø hypercar rarity and Scandinavian carbon craft.' },
  { slug: 'pininfarina', name: 'Pininfarina', country: 'Italy', foundedYear: 1930, domains: ['car'], description: 'Cambiano design house and Battista electric hypercar.' },
  { slug: 'gordon-murray-automotive', name: 'Gordon Murray Automotive', country: 'United Kingdom', foundedYear: 2017, domains: ['car'], description: 'T.50 fan-car purity and lightweight doctrine.' },
  { slug: 'ruf', name: 'Ruf', country: 'Germany', foundedYear: 1939, domains: ['car'], description: 'Pfaffenhausen Porsche-based manufacturer cars.' },
  { slug: 'alpina', name: 'Alpina', country: 'Germany', foundedYear: 1965, domains: ['car'], description: 'Buchloe BMW-based grand touring manufacturer cars.' },
  { slug: 'brabus', name: 'Brabus', country: 'Germany', foundedYear: 1977, domains: ['car'], description: 'Bottrop high-performance Mercedes craftsmanship.' },
  { slug: 'singer', name: 'Singer', country: 'United States', foundedYear: 2009, domains: ['car'], description: 'California reimagined 911 commissions for collectors.' },
  { slug: 'shelby', name: 'Shelby', country: 'United States', foundedYear: 1962, domains: ['car'], description: 'Carroll Shelby Cobra and American racing legend.' },
  { slug: 'ac-cars', name: 'AC Cars', country: 'United Kingdom', foundedYear: 1901, domains: ['car'], description: 'Thames Ditton Ace/Cobra roots and British sports DNA.' },
  { slug: 'hispano-suiza', name: 'Hispano-Suiza', country: 'Spain', foundedYear: 1904, domains: ['car'], description: 'Barcelona–Paris luxury and aviation-era prestige.' },
  { slug: 'facel-vega', name: 'Facel Vega', country: 'France', foundedYear: 1939, domains: ['car'], description: 'Parisian coachbuilt grand tourers of the jet age.' },
  { slug: 'iso', name: 'Iso', country: 'Italy', foundedYear: 1953, domains: ['car'], description: 'Bresso Grifo and Rivolta American-powered Italian GTs.' },
  { slug: 'lagonda', name: 'Lagonda', country: 'United Kingdom', foundedYear: 1906, domains: ['car'], description: 'Aston-linked luxury marque with Art Deco memory.' },
  { slug: 'maybach', name: 'Maybach', country: 'Germany', foundedYear: 1909, domains: ['car'], description: 'Ultra-luxury saloons under the Mercedes-Maybach crest.' },
  { slug: 'genesis', name: 'Genesis', country: 'South Korea', foundedYear: 2015, domains: ['car'], description: 'Hyundai luxury division with athletic design language.' },
  { slug: 'apollo', name: 'Apollo', country: 'Germany', foundedYear: 2004, domains: ['car'], description: 'Intensa Emozione track hypercar rarity.' },
  { slug: 'czinger', name: 'Czinger', country: 'United States', foundedYear: 2019, domains: ['car'], description: 'Los Angeles additive-manufactured hypercar craft.' },
  { slug: 'hennessey', name: 'Hennessey', country: 'United States', foundedYear: 1991, domains: ['car'], description: 'Texas Venom megacar performance and tuning heritage.' },
  { slug: 'ssc', name: 'SSC', country: 'United States', foundedYear: 1998, domains: ['car'], description: 'West Richland Tuatara speed-record hypercar program.' },

  // —— Motorcycles (primary) ——
  { key: 'yamaha', slug: 'yamaha', name: 'Yamaha', country: 'Japan', foundedYear: 1955, domains: ['motorcycle'], description: 'Sculptural supersport motorcycles with track presence.' },
  { key: 'ducati', slug: 'ducati', name: 'Ducati', country: 'Italy', foundedYear: 1926, domains: ['motorcycle'], description: 'Bologna superbike geometry and Desmo lore.' },
  { key: 'harley', slug: 'harley-davidson', name: 'Harley-Davidson', country: 'United States', foundedYear: 1903, domains: ['motorcycle'], description: 'Milwaukee cruiser heritage and tank-badge presence.' },
  { key: 'suzuki', slug: 'suzuki', name: 'Suzuki', country: 'Japan', foundedYear: 1909, domains: ['motorcycle'], description: 'Japanese road craft spanning café builds and superbikes.' },
  { key: 'honda', slug: 'honda', name: 'Honda', country: 'Japan', foundedYear: 1948, domains: ['motorcycle'], description: 'Custom and production motorcycle craft across every chamber.' },
  { key: 'ktm', slug: 'ktm', name: 'KTM', country: 'Austria', foundedYear: 1934, domains: ['motorcycle'], description: 'Orange-framed Race Ready roadsters and off-road DNA.' },
  { slug: 'bmw-motorrad', name: 'BMW Motorrad', country: 'Germany', foundedYear: 1923, domains: ['motorcycle'], description: 'Boxer and S 1000 RR engineering from Munich.' },
  { slug: 'triumph', name: 'Triumph', country: 'United Kingdom', foundedYear: 1902, domains: ['motorcycle'], description: 'Hinckley modern classics and Bonneville lineage.' },
  { slug: 'aprilia', name: 'Aprilia', country: 'Italy', foundedYear: 1945, domains: ['motorcycle'], description: 'Noale racing-bred sports bikes and RSV theatre.' },
  { slug: 'moto-guzzi', name: 'Moto Guzzi', country: 'Italy', foundedYear: 1921, domains: ['motorcycle'], description: 'Mandello transverse V-twin character and eagle crest.' },
  { slug: 'mv-agusta', name: 'MV Agusta', country: 'Italy', foundedYear: 1945, domains: ['motorcycle'], description: 'Cascina Costa red-and-silver racing aristocracy.' },
  { slug: 'indian', name: 'Indian', country: 'United States', foundedYear: 1901, domains: ['motorcycle'], description: 'America’s oldest motorcycle marque revived in Spirit Lake.' },
  { slug: 'royal-enfield', name: 'Royal Enfield', country: 'India', foundedYear: 1901, domains: ['motorcycle'], description: 'Chennai classic twins and Himalayan adventure language.' },
  { slug: 'kawasaki', name: 'Kawasaki', country: 'Japan', foundedYear: 1896, domains: ['motorcycle'], description: 'Akashi Ninja supersport and Z performance lineage.' },
  { slug: 'husqvarna', name: 'Husqvarna', country: 'Sweden', foundedYear: 1903, domains: ['motorcycle'], description: 'Swedish-born off-road and Vitpilen design craft.' },
  { slug: 'norton', name: 'Norton', country: 'United Kingdom', foundedYear: 1898, domains: ['motorcycle'], description: 'British racing Contour and Commando heritage.' },
  { slug: 'bimota', name: 'Bimota', country: 'Italy', foundedYear: 1973, domains: ['motorcycle'], description: 'Rimini chassis artistry and scarce sports frames.' },
  { slug: 'benelli', name: 'Benelli', country: 'Italy', foundedYear: 1911, domains: ['motorcycle'], description: 'Pesaro six-cylinder legend and modern roadsters.' },
  { slug: 'buell', name: 'Buell', country: 'United States', foundedYear: 1983, domains: ['motorcycle'], description: 'Erik Buell American sports-bike engineering.' },
  { slug: 'arch', name: 'Arch', country: 'United States', foundedYear: 2011, domains: ['motorcycle'], description: 'KRGT-1 and Method 143 collector motorcycles.' },
  { slug: 'vincent', name: 'Vincent', country: 'United Kingdom', foundedYear: 1928, domains: ['motorcycle'], description: 'Stevenage Black Shadow myth and postwar power.' },
  { slug: 'bsa', name: 'BSA', country: 'United Kingdom', foundedYear: 1861, domains: ['motorcycle'], description: 'Birmingham Small Arms classic British motorcycles.' },
  { slug: 'matchless', name: 'Matchless', country: 'United Kingdom', foundedYear: 1899, domains: ['motorcycle'], description: 'Woolwich AJS/Matchless twin heritage.' },
  { slug: 'ajs', name: 'AJS', country: 'United Kingdom', foundedYear: 1909, domains: ['motorcycle'], description: 'Wolverhampton racing and road twin lineage.' },
  { slug: 'gasgas', name: 'GASGAS', country: 'Spain', foundedYear: 1985, domains: ['motorcycle'], description: 'Catalan off-road and trial competition machines.' },
  { slug: 'sherco', name: 'Sherco', country: 'France', foundedYear: 1998, domains: ['motorcycle'], description: 'Nîmes enduro and trial specialist craft.' },
  { slug: 'beta', name: 'Beta', country: 'Italy', foundedYear: 1904, domains: ['motorcycle'], description: 'Florence trial and enduro competition bikes.' },
  { slug: 'livewire', name: 'LiveWire', country: 'United States', foundedYear: 2019, domains: ['motorcycle'], description: 'Harley-linked electric motorcycle house.' },
  { slug: 'energica', name: 'Energica', country: 'Italy', foundedYear: 2014, domains: ['motorcycle'], description: 'Modena electric superbike racing and Ego road craft.' },
  { slug: 'zero-motorcycles', name: 'Zero Motorcycles', country: 'United States', foundedYear: 2006, domains: ['motorcycle'], description: 'Scotts Valley electric street and adventure bikes.' },
  { slug: 'ccm', name: 'CCM', country: 'United Kingdom', foundedYear: 1971, domains: ['motorcycle'], description: 'Bolton Spitfire and hand-built British roadsters.' },
  { slug: 'moto-morini', name: 'Moto Morini', country: 'Italy', foundedYear: 1937, domains: ['motorcycle'], description: 'Bologna V-twin character and modern Milano craft.' },
  { slug: 'gilera', name: 'Gilera', country: 'Italy', foundedYear: 1909, domains: ['motorcycle'], description: 'Arcore Grand Prix heritage under Piaggio.' },
  { slug: 'laverda', name: 'Laverda', country: 'Italy', foundedYear: 1873, domains: ['motorcycle'], description: 'Breganze triple sports bikes and endurance lore.' },
  { slug: 'cagiva', name: 'Cagiva', country: 'Italy', foundedYear: 1978, domains: ['motorcycle'], description: 'Varese elephant-badge sports and adventure machines.' },

  // —— Watches (secondary) ——
  { key: 'patek', slug: 'patek-philippe', name: 'Patek Philippe', country: 'Switzerland', foundedYear: 1839, domains: ['watch'], description: 'Geneva complications and archival horology.' },
  { key: 'omega', slug: 'omega', name: 'Omega', country: 'Switzerland', foundedYear: 1848, domains: ['watch'], description: 'Precision instruments with expedition heritage.' },
  { key: 'rolex', slug: 'rolex', name: 'Rolex', country: 'Switzerland', foundedYear: 1905, domains: ['watch'], description: 'Tool-watch language and chronometer heritage.' },
  { key: 'cartier', slug: 'cartier', name: 'Cartier', country: 'France', foundedYear: 1847, domains: ['watch'], description: 'Early pilot wristwatch geometry still shaping dress codes.' },
  { slug: 'audemars-piguet', name: 'Audemars Piguet', country: 'Switzerland', foundedYear: 1875, domains: ['watch'], description: 'Le Brassus Royal Oak and haute complications.' },
  { slug: 'vacheron-constantin', name: 'Vacheron Constantin', country: 'Switzerland', foundedYear: 1755, domains: ['watch'], description: 'Geneva’s oldest continuous manufacture.' },
  { slug: 'a-lange-sohne', name: 'A. Lange & Söhne', country: 'Germany', foundedYear: 1845, domains: ['watch'], description: 'Glashütte Germanic finishing and Lange 1 architecture.' },
  { slug: 'jaeger-lecoultre', name: 'Jaeger-LeCoultre', country: 'Switzerland', foundedYear: 1833, domains: ['watch'], description: 'Vallée de Joux Reverso and calibre inventiveness.' },
  { slug: 'breguet', name: 'Breguet', country: 'Switzerland', foundedYear: 1775, domains: ['watch'], description: 'Abraham-Louis Breguet complications and Classique poetry.' },
  { slug: 'blancpain', name: 'Blancpain', country: 'Switzerland', foundedYear: 1735, domains: ['watch'], description: 'Fifty Fathoms dive heritage and Le Brassus craft.' },
  { slug: 'iwc', name: 'IWC', country: 'Switzerland', foundedYear: 1868, domains: ['watch'], description: 'Schaffhausen pilot and Portugieser instruments.' },
  { slug: 'panerai', name: 'Panerai', country: 'Italy', foundedYear: 1860, domains: ['watch'], description: 'Florentine dive-watch presence and Luminor cushion cases.' },
  { slug: 'tag-heuer', name: 'TAG Heuer', country: 'Switzerland', foundedYear: 1860, domains: ['watch'], description: 'La Chaux-de-Fonds chronograph racing culture.' },
  { slug: 'breitling', name: 'Breitling', country: 'Switzerland', foundedYear: 1884, domains: ['watch'], description: 'Aviation chronographs and Navitimer tool language.' },
  { slug: 'zenith', name: 'Zenith', country: 'Switzerland', foundedYear: 1865, domains: ['watch'], description: 'Le Locle El Primero high-beat chronograph lore.' },
  { slug: 'piaget', name: 'Piaget', country: 'Switzerland', foundedYear: 1874, domains: ['watch'], description: 'Ultra-thin dress watches and gold craftsmanship.' },
  { slug: 'girard-perregaux', name: 'Girard-Perregaux', country: 'Switzerland', foundedYear: 1791, domains: ['watch'], description: 'La Chaux-de-Fonds bridges and tourbillon history.' },
  { slug: 'chopard', name: 'Chopard', country: 'Switzerland', foundedYear: 1860, domains: ['watch'], description: 'L.U.C manufacture and Mille Miglia sports watches.' },
  { slug: 'hublot', name: 'Hublot', country: 'Switzerland', foundedYear: 1980, domains: ['watch'], description: 'Nyon Big Bang fusion materials language.' },
  { slug: 'richard-mille', name: 'Richard Mille', country: 'Switzerland', foundedYear: 2001, domains: ['watch'], description: 'Les Breuleux racing-grade haute complications.' },
  { slug: 'fp-journe', name: 'F.P. Journe', country: 'Switzerland', foundedYear: 1999, domains: ['watch'], description: 'Geneva independent resonance and Chronomètre lore.' },
  { slug: 'grand-seiko', name: 'Grand Seiko', country: 'Japan', foundedYear: 1960, domains: ['watch'], description: 'Shinshu Zaratsu finishing and Spring Drive precision.' },
  { slug: 'seiko', name: 'Seiko', country: 'Japan', foundedYear: 1881, domains: ['watch'], description: 'Tokyo quartz revolution and Prospex dive tools.' },
  { slug: 'tudor', name: 'Tudor', country: 'Switzerland', foundedYear: 1926, domains: ['watch'], description: 'Rolex sibling tool watches and Black Bay presence.' },
  { slug: 'longines', name: 'Longines', country: 'Switzerland', foundedYear: 1832, domains: ['watch'], description: 'Saint-Imier winged-hourglass elegance and chronographs.' },
  { slug: 'oris', name: 'Oris', country: 'Switzerland', foundedYear: 1904, domains: ['watch'], description: 'Hölstein independent mechanical watches.' },
  { slug: 'nomos', name: 'Nomos', country: 'Germany', foundedYear: 1990, domains: ['watch'], description: 'Glashütte Bauhaus clarity and in-house calibres.' },
  { slug: 'junghans', name: 'Junghans', country: 'Germany', foundedYear: 1861, domains: ['watch'], description: 'Schramberg Max Bill design and radio-controlled precision.' },
  { slug: 'hamilton', name: 'Hamilton', country: 'Switzerland', foundedYear: 1892, domains: ['watch'], description: 'American-Swiss railway and Khaki field instruments.' },
  { slug: 'tissot', name: 'Tissot', country: 'Switzerland', foundedYear: 1853, domains: ['watch'], description: 'Le Locle accessible Swiss craft and PRX geometry.' },
  { slug: 'bulgari', name: 'Bulgari', country: 'Italy', foundedYear: 1884, domains: ['watch'], description: 'Roman Octo Finissimo ultra-thin haute horology.' },
  { slug: 'chanel', name: 'Chanel', country: 'France', foundedYear: 1987, domains: ['watch'], description: 'Première and J12 design watches from Paris.' },
  { slug: 'hermes', name: 'Hermès', country: 'France', foundedYear: 1837, domains: ['watch'], description: 'Paris house craft with in-house H1912 movements.' },
  { slug: 'van-cleef-arpels', name: 'Van Cleef & Arpels', country: 'France', foundedYear: 1906, domains: ['watch'], description: 'Poetic complications and high jewellery timepieces.' },
  { slug: 'harry-winston', name: 'Harry Winston', country: 'United States', foundedYear: 1932, domains: ['watch'], description: 'New York Histoire de Tourbillon high jewellery watches.' },
  { slug: 'mbandf', name: 'MB&F', country: 'Switzerland', foundedYear: 2005, domains: ['watch'], description: 'Geneva Horological Machines and Legacy Machines.' },
  { slug: 'urwerk', name: 'Urwerk', country: 'Switzerland', foundedYear: 1997, domains: ['watch'], description: 'Geneva satellite wandering-hour futurism.' },
  { slug: 'h-moser', name: 'H. Moser & Cie.', country: 'Switzerland', foundedYear: 1828, domains: ['watch'], description: 'Neuhausen fumé dials and Concept watch minimalism.' },
  { slug: 'parmigiani', name: 'Parmigiani Fleurier', country: 'Switzerland', foundedYear: 1996, domains: ['watch'], description: 'Fleurier restoration-rooted haute manufacture.' },
  { slug: 'glashutte-original', name: 'Glashütte Original', country: 'Germany', foundedYear: 1845, domains: ['watch'], description: 'Saxon panorama date and manufacture finishing.' },
  { slug: 'ulysse-nardin', name: 'Ulysse Nardin', country: 'Switzerland', foundedYear: 1846, domains: ['watch'], description: 'Le Locle marine chronometer and Freak innovation.' },
  { slug: 'jaquet-droz', name: 'Jaquet Droz', country: 'Switzerland', foundedYear: 1738, domains: ['watch'], description: 'La Chaux-de-Fonds automata and enamel artistry.' },
  { slug: 'roger-dubuis', name: 'Roger Dubuis', country: 'Switzerland', foundedYear: 1995, domains: ['watch'], description: 'Meyrin Excalibur skeletonised haute spectacle.' },
  { slug: 'franck-muller', name: 'Franck Muller', country: 'Switzerland', foundedYear: 1991, domains: ['watch'], description: 'Genthod Cintrée Curvex and Master of Complications.' },
  { slug: 'jacob-co', name: 'Jacob & Co.', country: 'United States', foundedYear: 1986, domains: ['watch'], description: 'New York Astronomia and high jewellery theatre.' },
  { slug: 'bell-ross', name: 'Bell & Ross', country: 'France', foundedYear: 1992, domains: ['watch'], description: 'Instrument watches rooted in aviation cockpits.' },
  { slug: 'sinn', name: 'Sinn', country: 'Germany', foundedYear: 1961, domains: ['watch'], description: 'Frankfurt tool watches and Tegiment hardening.' },
  { slug: 'fortis', name: 'Fortis', country: 'Switzerland', foundedYear: 1912, domains: ['watch'], description: 'Grenchen aerospace chronographs and Flieger tools.' },
  { slug: 'ball', name: 'Ball Watch', country: 'Switzerland', foundedYear: 1891, domains: ['watch'], description: 'American railroad accuracy revived in Swiss form.' },
  { slug: 'eberhard', name: 'Eberhard & Co.', country: 'Switzerland', foundedYear: 1887, domains: ['watch'], description: 'La Chaux-de-Fonds Contograf and Chrono 4 invention.' },
  { slug: 'universal-geneve', name: 'Universal Genève', country: 'Switzerland', foundedYear: 1894, domains: ['watch'], description: 'Polerouter and Compax mid-century collector icons.' },
  { slug: 'citizen', name: 'Citizen', country: 'Japan', foundedYear: 1918, domains: ['watch'], description: 'Tokyo Eco-Drive and The Citizen precision.' },
  { slug: 'rado', name: 'Rado', country: 'Switzerland', foundedYear: 1917, domains: ['watch'], description: 'Lengnau high-tech ceramic design watches.' },
  { slug: 'maurice-lacroix', name: 'Maurice Lacroix', country: 'Switzerland', foundedYear: 1975, domains: ['watch'], description: 'Saignelégier Aikon and Masterpiece complications.' },
  { slug: 'frederique-constant', name: 'Frederique Constant', country: 'Switzerland', foundedYear: 1988, domains: ['watch'], description: 'Plan-les-Ouates accessible manufacture craft.' },
  { slug: 'raymond-weil', name: 'Raymond Weil', country: 'Switzerland', foundedYear: 1976, domains: ['watch'], description: 'Geneva independent family maison elegance.' },
];

export const CATEGORY_CATALOG = [
  { key: 'carIcons', slug: 'automotive-icons', name: 'Automotive icons', productType: 'car', description: 'Scarce silhouettes and engineering lore that define the chamber.' },
  { slug: 'hypercars', name: 'Hypercars', productType: 'car', description: 'Limited megacar and hybrid theatre beyond the supercar line.' },
  { slug: 'grand-tourers', name: 'Grand tourers', productType: 'car', description: 'Long-legged coupes built for continent-crossing presence.' },
  { slug: 'classic-sports-cars', name: 'Classic sports cars', productType: 'car', description: 'Postwar and golden-age roadsters still studied as plates.' },
  { slug: 'luxury-saloons', name: 'Luxury saloons', productType: 'car', description: 'Flagship saloons and ultra-luxury four-door craft.' },
  { key: 'motoCraft', slug: 'two-wheel-craft', name: 'Two-wheel craft', productType: 'motorcycle', description: 'Superbikes and heritage roadsters across the primary chamber.' },
  { slug: 'superbikes', name: 'Superbikes', productType: 'motorcycle', description: 'Track-bred sports machines and homologation specials.' },
  { slug: 'cruisers-tourers', name: 'Cruisers & tourers', productType: 'motorcycle', description: 'Long-distance twins, baggers, and road theatre.' },
  { slug: 'cafe-custom', name: 'Café & custom', productType: 'motorcycle', description: 'Café racers, scramblers, and workshop-built character.' },
  { slug: 'adventure-trail', name: 'Adventure & trail', productType: 'motorcycle', description: 'Dual-sport and enduro machines for mixed terrain.' },
  { key: 'watchChamber', slug: 'watch-chamber', name: 'Watch chamber', productType: 'watch', description: 'Secondary luxury watch archive for collector study.' },
  { slug: 'haute-complications', name: 'Haute complications', productType: 'watch', description: 'Tourbillons, perpetual calendars, and manufacture showpieces.' },
  { slug: 'sports-chronographs', name: 'Sports chronographs', productType: 'watch', description: 'Racing and tool chronographs with archival presence.' },
  { slug: 'dive-instruments', name: 'Dive instruments', productType: 'watch', description: 'Professional and heritage dive watches.' },
  { slug: 'dress-elegance', name: 'Dress elegance', productType: 'watch', description: 'Thin dress watches and jewellery-house timepieces.' },
];
