/**
 * Archive product plates for seed — brand-correct Unsplash photography.
 * Brands/categories are resolved by slug (or legacy key) in seedDemo.
 */
export function img(url, alt, type = 'gallery', sortOrder = 0, width = 1400, height = 933) {
  return { url, alt, type, sortOrder, width, height };
}

export function unsplash(id, w = 1400) {
  return `https://images.unsplash.com/${id}?auto=format&fit=max&w=${w}&q=80`;
}

/** @param {{ brands: Record<string, any>, categories: Record<string, any>, tags: Record<string, any>, buildSpecifications: Function }} ctx */
export function buildProductCatalog({ brands, categories, tags, buildSpecifications }) {
  const b = (slugOrKey) => {
    const doc = brands[slugOrKey];
    if (!doc) throw new Error(`[seed] Missing brand: ${slugOrKey}`);
    return doc._id;
  };
  const c = (slugOrKey) => {
    const doc = categories[slugOrKey];
    if (!doc) throw new Error(`[seed] Missing category: ${slugOrKey}`);
    return doc._id;
  };

  return [
    {
      name: 'Mercedes-Benz 300 SL',
      slug: 'mercedes-benz-300-sl',
      reference: 'AX-0001',
      productType: 'car',
      brand: b('mercedes'),
      category: c('carIcons'),
      tags: [tags.iconic._id, tags.heritage._id],
      shortDescription: 'The Gullwing coupe that defined postwar sports-car theatre.',
      description: 'Space-frame chassis and upward-hinging doors — archival engineering and collector myth.',
      releaseYear: 1955,
      productionPeriod: '1954–1957',
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      materials: ['aluminium', 'steel'],
      colors: ['silver'],
      images: [
        img(unsplash('photo-1772550327967-4d9123809a65'), 'Silver Mercedes-Benz 300 SL Gullwing coupe', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'Inline-6',
        power: '215 PS',
        bodyStyle: 'coupe',
        productionPeriod: '1954–1957',
      }),
    },
    {
      name: 'Bugatti Chiron',
      slug: 'bugatti-chiron',
      reference: 'AX-0057',
      productType: 'car',
      brand: b('bugatti'),
      category: c('carIcons'),
      tags: [tags.iconic._id],
      shortDescription: 'Molsheim’s modern hypercar — horseshoe grille and W16 theatre.',
      description: 'Eight-eye lamps, quad-turbo W16 presence, and contemporary Bugatti geometry.',
      releaseYear: 2016,
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1544636331-e26879cd4d9b'), 'White Bugatti Chiron front study at night', 'hero', 0),
      ],
      specifications: buildSpecifications('car', { engine: 'W16 quad-turbo', bodyStyle: 'coupe' }),
    },
    {
      name: 'Ferrari F40',
      slug: 'ferrari-f40',
      reference: 'AX-0108',
      productType: 'car',
      brand: b('ferrari'),
      category: c('carIcons'),
      tags: [tags.iconic._id],
      shortDescription: 'Twin-turbo V8 legend — raw engineering made collectible myth.',
      description: 'Enzo’s final road car and a cornerstone of modern collector mythology.',
      releaseYear: 1987,
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1750712344309-b62744ffae18'), 'Black Ferrari F40 on display', 'hero', 0),
        img(unsplash('photo-1726739569681-14cc0392b4bc'), 'Red Ferrari F40 in garage light', 'gallery', 1),
        img(unsplash('photo-1762111215490-0afdb55466c2'), 'Cream Ferrari F40 on the street', 'gallery', 2),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V8 twin-turbo',
        power: '478 PS',
        aspiration: 'twin-turbo',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'Porsche 911 Carrera 4',
      slug: 'porsche-911-carrera',
      reference: 'AX-0911',
      productType: 'car',
      brand: b('porsche'),
      category: c('carIcons'),
      tags: [tags.iconic._id],
      shortDescription: 'The enduring 911 silhouette — precision, balance, and collector continuity.',
      description: 'A modern Carrera 4 plate for the demonstration archive.',
      releaseYear: 2019,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1578911717720-4272f961231b'), 'Porsche 911 Carrera 4 rear badge study', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'Flat-six',
        drivetrain: 'AWD',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'Lamborghini Huracán',
      slug: 'lamborghini-huracan',
      reference: 'AX-0012',
      productType: 'car',
      brand: b('lamborghini'),
      category: c('carIcons'),
      tags: [tags.iconic._id],
      shortDescription: 'Sant’Agata V10 wedge — sharp lamps and hexagonal intake geometry.',
      description: 'Modern bull presence for the automotive chamber.',
      releaseYear: 2014,
      rarity: 'RARE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1519245659620-e859806a8d3b'), 'Dark grey Lamborghini Huracán with racing stripes', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V10',
        drivetrain: 'AWD',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'McLaren P1',
      slug: 'mclaren-p1',
      reference: 'AX-0003',
      productType: 'car',
      brand: b('mclaren'),
      category: c('carIcons'),
      tags: [tags.iconic._id, tags.competition._id],
      shortDescription: 'Hybrid hypercar craftsmanship with motorsport bloodline.',
      description: 'Woking’s hybrid flagship — demonstration plate for modern hypercar craft.',
      releaseYear: 2013,
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1748028265529-0be0aee7f674'), 'McLaren P1 displayed front view', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V8 hybrid',
        aspiration: 'twin-turbo',
        bodyStyle: 'coupe',
        productionUnits: '375',
      }),
    },
    {
      name: 'Aston Martin DB11',
      slug: 'aston-martin-db11',
      reference: 'AX-0DB11',
      productType: 'car',
      brand: b('aston-martin'),
      category: c('grand-tourers'),
      tags: [tags.iconic._id],
      shortDescription: 'Gaydon grand touring elegance with Bond-era silhouette memory.',
      description: 'Long-legged GT presence for the automotive chamber.',
      releaseYear: 2016,
      rarity: 'RARE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1743889291767-91037322b6c1'), 'Red Aston Martin grand tourer in sunlight', 'hero', 0),
      ],
      specifications: buildSpecifications('car', { engine: 'V12', bodyStyle: 'coupe' }),
    },
    {
      name: 'Jaguar E-Type',
      slug: 'jaguar-e-type',
      reference: 'AX-0ETYPE',
      productType: 'car',
      brand: b('jaguar'),
      category: c('classic-sports-cars'),
      tags: [tags.iconic._id, tags.heritage._id],
      shortDescription: 'Coventry feline silhouette — still the archive’s most studied sports car line.',
      description: 'Series-era E-Type geometry for classic sports-car study.',
      releaseYear: 1961,
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1494976388531-d1058494cdd8'), 'Classic Jaguar sports car on open road', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'Inline-6',
        bodyStyle: 'coupe',
        productionPeriod: '1961–1975',
      }),
    },
    {
      name: 'BMW M4 Competition',
      slug: 'bmw-m4-competition',
      reference: 'AX-0M4',
      productType: 'car',
      brand: b('bmw'),
      category: c('carIcons'),
      tags: [tags.competition._id],
      shortDescription: 'Munich M-division theatre — grille presence and track-bred road craft.',
      description: 'Modern Competition plate for the sports-saloon lineage.',
      releaseYear: 2021,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1555215695-3004980ad54e'), 'BMW M performance coupe front study', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'Inline-6 twin-turbo',
        drivetrain: 'RWD',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'Ford GT',
      slug: 'ford-gt',
      reference: 'AX-0FGT',
      productType: 'car',
      brand: b('ford'),
      category: c('hypercars'),
      tags: [tags.iconic._id, tags.competition._id],
      shortDescription: 'American Le Mans myth reborn as a modern mid-engine plate.',
      description: 'GT heritage for the hypercar chamber.',
      releaseYear: 2017,
      rarity: 'ULTRA-RARE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1727431682397-e1ffda5e0ca3'), 'Ford GT40 heritage lineup at Silverstone', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V6 twin-turbo',
        bodyStyle: 'coupe',
        productionUnits: 'limited',
      }),
    },
    {
      name: 'Chevrolet Corvette C8',
      slug: 'chevrolet-corvette-c8',
      reference: 'AX-0C8',
      productType: 'car',
      brand: b('chevrolet'),
      category: c('carIcons'),
      tags: [tags.iconic._id],
      shortDescription: 'Mid-engine Corvette lineage — American sports-car continuity.',
      description: 'C8 plate for the automotive chamber.',
      releaseYear: 2020,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1552519507-da3b142c6e3d'), 'Chevrolet Corvette on coastal road', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V8',
        drivetrain: 'RWD',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'Nissan GT-R',
      slug: 'nissan-gt-r',
      reference: 'AX-0GTR',
      productType: 'car',
      brand: b('nissan'),
      category: c('carIcons'),
      tags: [tags.iconic._id, tags.competition._id],
      shortDescription: 'Godzilla mythology — AWD grip and Japanese performance lore.',
      description: 'R35-era GT-R for the chamber.',
      releaseYear: 2009,
      rarity: 'RARE',
      availability: 'private',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1605559424843-9e4c228bf1c2'), 'Nissan GT-R in night urban light', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V6 twin-turbo',
        drivetrain: 'AWD',
        bodyStyle: 'coupe',
      }),
    },
    {
      name: 'Rolls-Royce Ghost',
      slug: 'rolls-royce-ghost',
      reference: 'AX-0GHOST',
      productType: 'car',
      brand: b('rolls-royce'),
      category: c('luxury-saloons'),
      tags: [tags.heritage._id],
      shortDescription: 'Goodwood presence — Spirit of Ecstasy and quiet theatre.',
      description: 'Ultra-luxury saloon plate for the archive.',
      releaseYear: 2020,
      rarity: 'RARE',
      availability: 'private',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1631295868223-63265b40d9e4'), 'White Rolls-Royce luxury saloon', 'hero', 0),
      ],
      specifications: buildSpecifications('car', {
        engine: 'V12',
        bodyStyle: 'saloon',
      }),
    },
    {
      name: 'Harley-Davidson Heritage',
      slug: 'harley-davidson-heritage',
      reference: 'AX-1916',
      productType: 'motorcycle',
      brand: b('harley'),
      category: c('motoCraft'),
      tags: [tags.heritage._id],
      shortDescription: 'Classic Milwaukee cruiser presence with long-road character.',
      description: 'Tank-badge heritage for the two-wheel chamber.',
      releaseYear: 1948,
      rarity: 'COLLECTIBLE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1459372537964-e38c57a5e86f'), 'Vintage Harley-Davidson motorcycle study', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'V-twin',
        productionPeriod: '1948',
      }),
    },
    {
      name: 'Suzuki Café Racer',
      slug: 'suzuki-cafe-racer',
      reference: 'AX-1919',
      productType: 'motorcycle',
      brand: b('suzuki'),
      category: c('cafe-custom'),
      tags: [tags.heritage._id],
      shortDescription: 'A stripped café-racer build with lean tank lines and workshop craft.',
      description: 'Custom Suzuki café geometry for the two-wheel chamber.',
      releaseYear: 1975,
      rarity: 'COLLECTIBLE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1508349661974-9927dbd8399c'), 'Custom Suzuki café racer motorcycle profile', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        modelGeneration: 'Café racer',
        productionPeriod: '1975',
      }),
    },
    {
      name: 'Ducati Panigale V4',
      slug: 'ducati-panigale',
      reference: 'AX-0DUC',
      productType: 'motorcycle',
      brand: b('ducati'),
      category: c('superbikes'),
      tags: [tags.iconic._id],
      shortDescription: 'Italian superbike form — winglet aero and Desmo character.',
      description: 'Bologna Panigale V4 presence for the two-wheel chamber.',
      releaseYear: 2018,
      rarity: 'COLLECTIBLE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1632157256334-518122d788bd'), 'Red Ducati Panigale V4 on mountain road', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'V4',
        finalDrive: 'chain',
      }),
    },
    {
      name: 'Honda Scrambler',
      slug: 'honda-scrambler',
      reference: 'AX-0HON',
      productType: 'motorcycle',
      brand: b('honda'),
      category: c('cafe-custom'),
      tags: [tags.heritage._id],
      shortDescription: 'Custom Honda scrambler craft — knobby tires and forest-road stance.',
      description: 'Demonstration Honda scrambler for the two-wheel chamber.',
      releaseYear: 1972,
      rarity: 'COLLECTIBLE',
      availability: 'private',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1502744688674-c619d1586c9e'), 'Custom Honda scrambler on forest trail', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', { modelGeneration: 'Scrambler' }),
    },
    {
      name: 'Yamaha YZF-R6',
      slug: 'yamaha-yzf-r6',
      reference: 'AX-0R6',
      productType: 'motorcycle',
      brand: b('yamaha'),
      category: c('superbikes'),
      tags: [tags.competition._id],
      shortDescription: 'Sculptural supersport craftsmanship with archival track presence.',
      description: 'A modern supersport plate for the motorcycle chamber.',
      releaseYear: 2008,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1609630875171-b1321377ee65'), 'Yamaha YZF-R6 orange and black superbike', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'Inline-4',
        displacement: '599 cc',
        transmission: '6-speed',
      }),
    },
    {
      name: 'KTM RC 390',
      slug: 'ktm-rc-390',
      reference: 'AX-0KTM',
      productType: 'motorcycle',
      brand: b('ktm'),
      category: c('superbikes'),
      tags: [tags.competition._id],
      shortDescription: 'Orange-framed Race Competition roadster energy.',
      description: 'KTM RC 390 for the two-wheel chamber.',
      releaseYear: 2014,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1449426468159-d96dbf08f19f'), 'KTM RC 390 sport motorcycle parked outdoors', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        displacement: '373 cc',
        modelGeneration: 'RC 390',
      }),
    },
    {
      name: 'Triumph Bonneville T120',
      slug: 'triumph-bonneville-t120',
      reference: 'AX-0BON',
      productType: 'motorcycle',
      brand: b('triumph'),
      category: c('cruisers-tourers'),
      tags: [tags.heritage._id],
      shortDescription: 'Hinckley modern classic — Bonneville lineage and British twin character.',
      description: 'Bonneville T120 plate for the two-wheel chamber.',
      releaseYear: 2016,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1558981403-c5f9899a28bc'), 'Triumph-style classic motorcycle study', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'Parallel twin',
        displacement: '1200 cc',
      }),
    },
    {
      name: 'Kawasaki Ninja ZX-10R',
      slug: 'kawasaki-ninja-zx-10r',
      reference: 'AX-0ZX10',
      productType: 'motorcycle',
      brand: b('kawasaki'),
      category: c('superbikes'),
      tags: [tags.competition._id],
      shortDescription: 'Akashi green supersport — WorldSBK bloodline on the road.',
      description: 'ZX-10R plate for the superbike chamber.',
      releaseYear: 2019,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1568772585407-9361f9bf3a87'), 'Kawasaki-style green supersport motorcycle', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'Inline-4',
        displacement: '998 cc',
      }),
    },
    {
      name: 'BMW S 1000 RR',
      slug: 'bmw-s1000rr',
      reference: 'AX-0S1K',
      productType: 'motorcycle',
      brand: b('bmw-motorrad'),
      category: c('superbikes'),
      tags: [tags.competition._id, tags.iconic._id],
      shortDescription: 'Munich superbike engineering — asymmetric headlamp lore and Race Ready geometry.',
      description: 'S 1000 RR for the two-wheel chamber.',
      releaseYear: 2019,
      rarity: 'RARE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1753476981086-d16060e71e35'), 'White BMW S 1000 RR motorcycle study', 'hero', 0),
      ],
      specifications: buildSpecifications('motorcycle', {
        engine: 'Inline-4',
        displacement: '999 cc',
      }),
    },
    {
      name: 'Patek Philippe Henry Graves Supercomplication',
      slug: 'patek-philippe-henry-graves-supercomplication',
      reference: 'AX-1933',
      productType: 'watch',
      brand: b('patek'),
      category: c('watchChamber'),
      tags: [tags.ultraRare._id, tags.heritage._id],
      shortDescription: 'A unique pocket-watch summit of twentieth-century complications.',
      description: 'Secondary-domain horology plate — demonstration stand-in for the Graves Supercomplication.',
      releaseYear: 1933,
      rarity: 'UNIQUE',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1509048191080-d2984bad6ae5'), 'Antique pocket watch', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'manual',
        productionPeriod: '1925–1933',
      }),
    },
    {
      name: 'Rolex Air-King',
      slug: 'rolex-air-king',
      reference: 'AX-0AIR',
      productType: 'watch',
      brand: b('rolex'),
      category: c('watchChamber'),
      tags: [tags.heritage._id],
      shortDescription: 'Aviation chronometer language preserved for collector study.',
      description: 'Secondary watch chamber plate.',
      releaseYear: 1945,
      rarity: 'RARE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1547996160-81dfa63595aa'), 'Rolex Air-King on book surface', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'automatic',
        bracelet: 'metal',
      }),
    },
    {
      name: 'Omega Seamaster Planet Ocean',
      slug: 'omega-seamaster-planet-ocean',
      reference: 'AX-0SEA',
      productType: 'watch',
      brand: b('omega'),
      category: c('dive-instruments'),
      tags: [tags.iconic._id, tags.heritage._id],
      shortDescription: 'Diving chronograph history with enduring archival significance.',
      description: 'Secondary watch chamber plate for the demonstration catalog.',
      releaseYear: 2005,
      rarity: 'ICONIC',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1523170335258-f5ed11844a49'), 'Omega Seamaster Planet Ocean chronograph', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'automatic',
        waterResistance: '300m',
        bracelet: 'metal',
      }),
    },
    {
      name: 'Cartier Santos',
      slug: 'cartier-santos',
      reference: 'AX-0SAN',
      productType: 'watch',
      brand: b('cartier'),
      category: c('dress-elegance'),
      tags: [tags.heritage._id],
      shortDescription: 'Early pilot wristwatch geometry still shaping dress codes.',
      description: 'Square case geometry as a quieter secondary-domain entry.',
      releaseYear: 1904,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1587836374828-4dbafa94cf0e'), 'Cartier-style square luxury watch', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        caseMaterial: 'steel/gold',
        dialColor: 'white',
        bracelet: 'metal',
      }),
    },
    {
      name: 'Audemars Piguet Royal Oak',
      slug: 'audemars-piguet-royal-oak',
      reference: 'AX-0AP',
      productType: 'watch',
      brand: b('audemars-piguet'),
      category: c('sports-chronographs'),
      tags: [tags.iconic._id],
      shortDescription: 'Le Brassus octagonal sports watch that redefined luxury tool language.',
      description: 'Royal Oak plate for the secondary chamber.',
      releaseYear: 1972,
      rarity: 'ICONIC',
      availability: 'private',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1614164185128-e4ec99c436d7'), 'Steel luxury sports watch with integrated bracelet', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'automatic',
        caseMaterial: 'steel',
        bracelet: 'metal',
      }),
    },
    {
      name: 'IWC Pilot’s Watch Chronograph',
      slug: 'iwc-pilots-chronograph',
      reference: 'AX-0IWC',
      productType: 'watch',
      brand: b('iwc'),
      category: c('sports-chronographs'),
      tags: [tags.heritage._id],
      shortDescription: 'Schaffhausen pilot instrument — clear dials and aviation tool memory.',
      description: 'Pilot chronograph for the secondary chamber.',
      releaseYear: 2016,
      rarity: 'COLLECTIBLE',
      availability: 'production',
      featured: false,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1524592094714-0f0654e20314'), 'Pilot-style chronograph wristwatch study', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'automatic',
        bracelet: 'leather',
      }),
    },
    {
      name: 'Grand Seiko Snowflake',
      slug: 'grand-seiko-snowflake',
      reference: 'AX-0GS',
      productType: 'watch',
      brand: b('grand-seiko'),
      category: c('dress-elegance'),
      tags: [tags.iconic._id],
      shortDescription: 'Shinshu Zaratsu finishing — textured dial atmosphere from Japan.',
      description: 'Snowflake plate for the secondary chamber.',
      releaseYear: 2017,
      rarity: 'RARE',
      availability: 'production',
      featured: true,
      status: 'approved',
      publisher: 'ArchiveX',
      images: [
        img(unsplash('photo-1533139502658-0198f920d8e8'), 'Dress chronometer with textured dial', 'hero', 0),
      ],
      specifications: buildSpecifications('watch', {
        movement: 'Spring Drive',
        dialColor: 'white',
        bracelet: 'metal',
      }),
    },
  ];
}
